# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/treasure_trove',
                'doc_host': 'https://CarperAI.github.io',
                'git_url': 'https://github.com/CarperAI/treasure_trove',
                'lib_path': 'treasure_trove'},
  'syms': {'treasure_trove.core': {'treasure_trove.core.foo': ('core.html#foo', 'treasure_trove/core.py')}}}
