# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/treasure_trove',
                'doc_host': 'https://CarperAI.github.io',
                'git_url': 'https://github.com/CarperAI/treasure_trove',
                'lib_path': 'treasure_trove'},
  'syms': { 'treasure_trove.core': { 'treasure_trove.core.classify': ('core.html#classify', 'treasure_trove/core.py'),
                                     'treasure_trove.core.filter_dataset': ('core.html#filter_dataset', 'treasure_trove/core.py'),
                                     'treasure_trove.core.label_dataset': ('core.html#label_dataset', 'treasure_trove/core.py'),
                                     'treasure_trove.core.train_labeler': ('core.html#train_labeler', 'treasure_trove/core.py')}}}
